/* Insert Admin User */
INSERT INTO `OSU-R6`.`Users` (`firstName`, `lastName`, `ign`, `email`, `password`, `admin`, `status`, `bio`, `pfp`, `role`, `createdAt`, `updatedAt`) VALUES ('Admin', 'User', 'ign1', 'admin@gmail.com', '$2b$08$bs0dshJaWfZgPWTydXBeRecTDdgjW0L1i2QXJHw7gx3p1YwDo.Qli', '1', 'inactive', 'This is the bio of Admin', null, 'Entry', '2023-04-29 01:09:56', '2023-04-29 01:09:56');
/* Insert Active Users */
INSERT INTO `OSU-R6`.`Users` (`firstName`, `lastName`, `ign`, `email`, `password`, `admin`, `status`, `bio`, `pfp`, `role`,  `createdAt`, `updatedAt`) VALUES ('Gavin', 'Gutowsky', 'Doggle', 'gavin@gmail.com', '$2b$08$bs0dshJaWfZgPWTydXBeRecTDdgjW0L1i2QXJHw7gx3p1YwDo.Qli', '0', 'active', 'This is the bio of Gavin', 'C:\\Users\\krist\\Documents\\WebDev\\osu-r6-api\\api\\uploads\\profile-images\\11ba11b92853706e427b42468461d096.png', 'Support', '2023-04-29 01:09:56', '2023-04-29 01:09:56');
INSERT INTO `OSU-R6`.`Users` (`firstName`, `lastName`, `ign`, `email`, `password`, `admin`, `status`, `bio`, `pfp`, `role`,  `createdAt`, `updatedAt`) VALUES ('Christian', 'Bergdorf', 'Soupzeit', 'christian@gmail.com', '$2b$08$bs0dshJaWfZgPWTydXBeRecTDdgjW0L1i2QXJHw7gx3p1YwDo.Qli', '0', 'active', 'This is the bio of Christian', 'C:\\Users\\krist\\Documents\\WebDev\\osu-r6-api\\api\\uploads\\profile-images\\124163b308b6cb036dccee6f640aed60.png', 'Support', '2023-04-29 01:09:56', '2023-04-29 01:09:56');
INSERT INTO `OSU-R6`.`Users` (`firstName`, `lastName`, `ign`, `email`, `password`, `admin`, `status`, `bio`, `pfp`, `role`,  `createdAt`, `updatedAt`) VALUES ('Connor', 'Smith', 'SweatyCarrot', 'connor@gmail.com', '$2b$08$bs0dshJaWfZgPWTydXBeRecTDdgjW0L1i2QXJHw7gx3p1YwDo.Qli', '0', 'active', "Connor Smith was a skilled gamer with lightning-fast reflexes and an extensive history of playing first-person shooters. His aim was impeccable, and his knowledge of game mechanics was unparalleled. However, there was one problem that plagued Connor's gaming journey he had an uncanny ability to inadvertently cause chaos for his teammates. 
 No matter how hard he tried, Connor couldn't seem to shake his habit of accidentally taking down his own comrades. It was as if his bullets had a magnet for friendly targets, leading to unfortunate friendly fire incidents and tactical blunders. Round after round, his actions threw his team into disarray, making victory an elusive dream.", 'C:\\Users\\krist\\Documents\\WebDev\\osu-r6-api\\api\\uploads\\profile-images\\fdc9cf9e60bd7c47b23daac755535df6.png', 'IGL', '2023-04-29 01:09:56', '2023-04-29 01:09:56');
INSERT INTO `OSU-R6`.`Users` (`firstName`, `lastName`, `ign`, `email`, `password`, `admin`, `status`, `bio`, `pfp`, `role`,  `createdAt`, `updatedAt`) VALUES ('Carl', 'Bohme', 'Sable', 'carl@gmail.com', '$2b$08$bs0dshJaWfZgPWTydXBeRecTDdgjW0L1i2QXJHw7gx3p1YwDo.Qli', '0', 'active', 'This is the bio of Carl', 'C:\\Users\\krist\\Documents\\WebDev\\osu-r6-api\\api\\uploads\\profile-images\\8c67b73308e4d707577a83b191e4b274.png', 'Entry', '2023-04-29 01:09:56', '2023-04-29 01:09:56');
INSERT INTO `OSU-R6`.`Users` (`firstName`, `lastName`, `ign`, `email`, `password`, `admin`, `status`, `bio`, `pfp`, `role`,  `createdAt`, `updatedAt`) VALUES ('Dylan', 'Shafer', 'ObamaMcgee', 'dylan@gmail.com', '$2b$08$bs0dshJaWfZgPWTydXBeRecTDdgjW0L1i2QXJHw7gx3p1YwDo.Qli', '0', 'active', 'This is the bio of Dylan', 'C:\\Users\\krist\\Documents\\WebDev\\osu-r6-api\\api\\uploads\\profile-images\\e2eea5e8510196d24c37d5c27a2b08aa.png', 'Flex', '2023-04-29 01:09:56', '2023-04-29 01:09:56');
